# Generated by Django 3.2.16 on 2023-11-23 16:40

from django.db import migrations, models

VIEWS_TO_REMOVE = [
    "uvwItemExpenditures",
    "uvwItemUtilization",
    "uvwServiceExpenditures",
    "uvwServiceUtilization",
]


def delete_views():
    sql_str = ''
    for view in VIEWS_TO_REMOVE:
        sql_str += f'DROP VIEW IF EXISTS "{view}";\n'
    return sql_str

class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_set_managed_to_true'),
    ]

    operations = [
        migrations.RunSQL(delete_views(), migrations.RunSQL.noop),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(db_column='ItemCode', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(db_column='ItemName', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.CharField(db_column='ServCode', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(db_column='ServName', max_length=255),
        ),
    ]
