# Generated by Django 3.2.16 on 2024-01-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_increase_code_name_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='nhia_code',
            field=models.CharField(blank=True, db_column='ItemNhiaCode', max_length=50, null=True),
        ),
    ]
