# Generated by Django 3.2.16 on 2023-11-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_increase_code_name_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='json_ext',
            field=models.JSONField(blank=True, db_column='JsonExt', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='json_ext',
            field=models.JSONField(blank=True, db_column='JsonExt', null=True),
        ),
    ]
